config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :line_items, only: [:index, :update, :show]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'line_items#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/campaign.rb
class Campaign < ApplicationRecord
  has_many :line_items
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  has_paper_trail

  belongs_to :campaign
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :set_paper_trail_whodunnit
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  before_action :authenticate_user!

  def index
    @line_items = LineItem.page params[:page]
  end

  def update
    line_item = LineItem.find(params[:id])
    line_item.update!(line_item_params)

    redirect_back(fallback_location: line_items_path)
  end

  def show
    @line_item = LineItem.find(params[:id])
  end

  def line_item_params
    params.require(:line_item).permit(:adjustments)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
  def prettify_changeset(version)
    updated_by = nil
    if version.whodunnit
      updated_by = User.find(version.whodunnit)
    end

    changeset = version.changeset
    updated_at = changeset.delete("updated_at").second
    summary = "At #{updated_at}, "

    changeset.each do |k, v|
      summary << "#{k} changed from #{v.first} to #{v.second}"
    end

    summary << " by #{updated_by.email}" if updated_by
    summary << "."

    summary
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Invoice</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
      <div class="container">
        <a class="navbar-brand" href="#">Invoice</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <%= render 'devise/menu/registration_items' %>
            <%= render 'devise/menu/login_items' %>
          </ul>
        </div>
      </div>
    </nav>

    <!-- Page Content -->
    <div class="container">
      <div class="row">
        <div class="col-lg-12 text-center">
          <% flash.each do |a, message| %>
            <div class="alert alert-success"><%= message %></div>
          <% end %>
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/line_items/index.html.erb
<h2 class="mt-5">LineItems#index</h2>
<table>
  <tr>
    <td>name</td>
    <td>booked amount</td>
    <td>actual amount</td>
    <td>adjustments</td>
    <td>campaign_id</td>
  </tr>
  <% @line_items.each do |li| %>
    <tr>
      <td><%= link_to(li.name, line_item_path(li)) %></td>
      <td><%= li.booked_amount %></td>
      <td><%= li.actual_amount %></td>
      <td>
          <%= form_for li do |f| %>
            <%= f.number_field :adjustments %>
            <%= f.submit "Update" %>
          <% end %>
      </td>
      <td><%= li.campaign_id %></td>
    </tr>
  <% end %>
</table>
<%= paginate @line_items %>

app/views/line_items/show.html.erb
<h2 class="mt-5">LineItems#show</h2>
<table>
  <tr>
    <td>name</td>
    <td>booked amount</td>
    <td>actual amount</td>
    <td>adjustments</td>
    <td>campaign_id</td>
  </tr>
  <tr>
    <td><%= @line_item.name %></td>
    <td><%= @line_item.booked_amount %></td>
    <td><%= @line_item.actual_amount %></td>
    <td>
        <%= form_for @line_item do |f| %>
          <%= f.number_field :adjustments %>
          <%= f.submit "Update" %>
        <% end %>
    </td>
    <td><%= @line_item.campaign_id %></td>
  </tr>
</table>

<h2>Changelog</h2>
<% if @line_item.versions.size == 1 %>
  No previous changes
<% else %>
  <ul>
    <% @line_item.versions.drop(1).reverse.each do |version| %>
      <li><%= prettify_changeset(version) %></li>
    <% end %>
  </ul>
<% end %>